export {default as Homepage} from "./Homepage"
export {default as Login} from "./Login"
export {default as FormRegist} from "./FormRegist"
export {default as Home} from "./Home"
export {default as PageWishlist} from "./PageWishlist"
export {default as PageRecomend} from "./PageRecomend"
export {default as Profile} from "./Profile"